name: terraform-workflow
on: [push]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
jobs:
  terraform-init:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.8

      - name: Terraform version
        id: version
        run: terraform version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: [terraform-init]
    defaults:
      run:
        working-directory: ./

    steps:
      - run: pwd && ls -al
      - name: Terraform plan
        id: plan
        run: terraform plan -var-file=./environments/sandbox/sandbox.tfvars -out tfplan